Hacks to build on Travis
Strange things are afoot at the Circle K. First of all, it is still true that
we need to use rustc 1.26 in order to avoid stack overflow problems on Travis.
Second, something totally bizarre is happening where the macOS compilers error
out on me unless I run them directly at the beginning of the build (?!):

```
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /Users/travis/miniconda3/conda-bld/tectonic_1537107322345/_build_env/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
cc: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
cc: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
```

(Doubly weird since I have no idea why we would be linking to CUPS!)

```
cargo:warning=sh: line 1:  3540 Trace/BPT trap: 5       /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk / -find ar 2> /dev/null
cargo:warning=ar: error: unable to find utility "ar", not a developer tool or in PATH
exit code: 72
```